import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fauxAssistantMessage } from "@earendil-works/pi-ai";
import { type FauxProviderRegistration, registerFauxProvider } from "@earendil-works/pi-ai/compat";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import piSuite from "../src/index.ts";

type Handler = (event: any, context: any) => any;

function createExtensionApi() {
	const commands = new Map<string, { handler: Handler }>();
	const handlers = new Map<string, Handler>();
	const pi = {
		registerCommand(name: string, command: { handler: Handler }) {
			commands.set(name, command);
		},
		on(event: string, handler: Handler) {
			handlers.set(event, handler);
		},
	};

	piSuite(pi as never);
	return { commands, handlers };
}

describe("Pi Suite extension", () => {
	let agentDirectory: string;
	let originalAgentDirectory: string | undefined;
	let fauxProvider: FauxProviderRegistration | undefined;

	beforeEach(() => {
		agentDirectory = mkdtempSync(join(tmpdir(), "pi-suite-agent-"));
		originalAgentDirectory = process.env.PI_CODING_AGENT_DIR;
		process.env.PI_CODING_AGENT_DIR = agentDirectory;
	});

	afterEach(() => {
		fauxProvider?.unregister();
		fauxProvider = undefined;
		if (originalAgentDirectory === undefined) delete process.env.PI_CODING_AGENT_DIR;
		else process.env.PI_CODING_AGENT_DIR = originalAgentDirectory;
		rmSync(agentDirectory, { recursive: true, force: true });
	});

	test("installs Explore globally, preserves customization, and disables upstream defaults", async () => {
		writeFileSync(join(agentDirectory, "subagents.json"), JSON.stringify({ maxConcurrent: 8 }), "utf8");
		const { commands } = createExtensionApi();
		const notify = vi.fn();

		await commands.get("setup-agents")?.handler("", { ui: { notify } });

		const explorePath = join(agentDirectory, "agents", "Explore.md");
		expect(readFileSync(explorePath, "utf8")).toContain("read-only codebase exploration specialist");
		expect(JSON.parse(readFileSync(join(agentDirectory, "subagents.json"), "utf8"))).toEqual({
			maxConcurrent: 8,
			disableDefaultAgents: true,
		});
		expect(notify).toHaveBeenCalledWith(
			"Installed 1 preset. Upstream default agents are disabled globally. Run /reload to use the presets.",
			"info",
		);

		const customizedExplore = "---\ndescription: Custom Explore\n---\nKeep this definition.\n";
		writeFileSync(explorePath, customizedExplore, "utf8");
		notify.mockClear();
		await commands.get("setup-agents")?.handler("", { ui: { notify } });

		expect(readFileSync(explorePath, "utf8")).toBe(customizedExplore);
		expect(notify).toHaveBeenCalledWith(
			"All presets were already installed. Left 1 existing definition unchanged. Upstream default agents are disabled globally. Run /reload to use the presets.",
			"info",
		);
	});

	test("persists a selected model across sessions and uses it for real native compaction", async () => {
		fauxProvider = registerFauxProvider({
			api: "pi-suite-compaction-test",
			provider: "test-provider",
			models: [{ id: "summary-model", name: "Summary Model", reasoning: true }],
		});
		const model = fauxProvider.getModel();
		let request:
			| {
					modelId: string;
					reasoning: unknown;
					prompt: string;
			  }
			| undefined;
		fauxProvider.setResponses([
			(context, options, _state, requestedModel) => {
				const firstMessage = context.messages[0];
				const summarizationOptions = options as { reasoning?: unknown } | undefined;
				request = {
					modelId: requestedModel.id,
					reasoning: summarizationOptions?.reasoning,
					prompt:
						firstMessage?.role === "user" && typeof firstMessage.content !== "string"
							? firstMessage.content[0]?.type === "text"
								? firstMessage.content[0].text
								: ""
							: "",
				};
				return fauxAssistantMessage("Summary generated by the selected model");
			},
		]);

		const settingsPath = join(agentDirectory, "settings.json");
		writeFileSync(settingsPath, JSON.stringify({ theme: "dark" }), "utf8");
		const firstSession = createExtensionApi();
		const notify = vi.fn();
		const context = {
			mode: "tui",
			hasUI: true,
			ui: {
				custom: vi.fn().mockResolvedValue({ type: "model", model }),
				select: vi.fn().mockResolvedValue("high"),
				notify,
			},
			modelRegistry: {
				getAvailable: () => [model],
				find: (provider: string, modelId: string) =>
					provider === model.provider && modelId === model.id ? model : undefined,
				getApiKeyAndHeaders: async () => ({ ok: true, apiKey: "faux-key" }),
			},
			sessionManager: { getBranch: () => [] },
		};

		await firstSession.commands.get("compaction-model")?.handler("", context);

		expect(JSON.parse(readFileSync(settingsPath, "utf8"))).toEqual({
			theme: "dark",
			piSuite: {
				compactionModel: {
					provider: "test-provider",
					modelId: "summary-model",
					thinkingLevel: "high",
				},
			},
		});

		const nextSession = createExtensionApi();
		for (const reason of ["startup", "reload", "resume"]) {
			notify.mockClear();
			await nextSession.handlers.get("session_start")?.({ reason }, context);
			expect(notify).toHaveBeenCalledWith("Compaction model: test-provider/summary-model (high thinking).", "info");
		}

		const signal = new AbortController().signal;
		const event = {
			preparation: {
				firstKeptEntryId: "kept-entry",
				messagesToSummarize: [
					{
						role: "user",
						content: [{ type: "text", text: "Keep this important decision." }],
						timestamp: Date.now(),
					},
				],
				turnPrefixMessages: [],
				isSplitTurn: false,
				tokensBefore: 100,
				fileOps: { read: new Set<string>(), written: new Set<string>(), edited: new Set<string>() },
				settings: { enabled: true, reserveTokens: 1_000, keepRecentTokens: 100 },
			},
			branchEntries: [],
			customInstructions: "Focus on decisions",
			signal,
		};

		const result = await nextSession.handlers.get("session_before_compact")?.(event, context);

		expect(result.compaction.summary).toContain("Summary generated by the selected model");
		expect(result.compaction.firstKeptEntryId).toBe("kept-entry");
		expect(request).toMatchObject({ modelId: "summary-model", reasoning: "high" });
		expect(request?.prompt).toContain("Focus on decisions");
		expect(fauxProvider.state.callCount).toBe(1);

		notify.mockClear();
		await nextSession.handlers.get("session_compact")?.(
			{
				fromExtension: true,
				compactionEntry: result.compaction,
				reason: "manual",
				willRetry: false,
			},
			context,
		);
		// Pi rebuilds the chat immediately after session_compact, so the extension
		// must wait until the next event-loop turn before showing the notification.
		expect(notify).not.toHaveBeenCalled();
		await new Promise((resolve) => setTimeout(resolve, 0));
		expect(notify).toHaveBeenCalledWith(
			"Compacted session with test-provider/summary-model (high thinking).",
			"info",
		);
	});
});
